### ISSUE TITLE
MWS FBA get_package_labels (GetPackageLabels) as PDF file

### ISSUE THREAD

**Issue by blairanderson** [hakanensari/peddler#118]
https://docs.developer.amazonservices.com/en_US/fba_inbound/FBAInbound_ExtractingPdfDocumentData.html

```ruby
get_content = client.fulfillment_inbound_shipment.get_package_labels(
  fba_shipment_id,
  page_type = "PackageLabel_Letter_2"
).parse

label_tempfile = Tempfile.new([fba_shipment_id, '.zip'])

File.open(label_tempfile, "wb") do |f|
  f.write(Base64.decode64(get_content.dig("TransportDocument", "PdfDocument")))
end

file_path = Rails.root.join('tmp', "#{fba_shipment_id}.pdf")

Zip::File.open(label_tempfile) do |zipfile|
  zipfile.each do |file|
    if file.name == "PackageLabels.pdf"
      File.delete(file_path) if File.exists?(file_path) # overwrite file if we call multiple times
      file.extract(file_path) # saves data to file_path
      labels = File.open(file_path) # this is how i'm persisting the files to my database/s3
      shipment.labels = labels # this is how i'm persisting the files to my database/s3
      shipment.save! # this is how i'm persisting the files to my database/s3
      labels.close # make sure file is closed
    end
  end
end
label_tempfile.close!
```

This lib parses CSV files from other parts of the API and might be a nice addition for the PDF as well.

not sure if/how/where you would accept this.

**Comment by blairanderson** [comment]
FYI @hakanensari thank you for this GEM. Amazing 👍

**Comment by hakanensari** [comment]
@blairanderson I’m not sure if there any other operations elsewhere in the API that serve PDFs. This could certainly be something useful.


 I’m off the grid now but will look into this when I return next month.

**Comment by blairanderson** [comment]
#close

**Comment by hakanensari** [comment]
@blairanderson sorry for the late response, and thanks for taking the time to post and explain.

I did some digging around and found that the Merchant Fulfilment API is also [embedding labels, but in a slightly different way](http://docs.developer.amazonservices.com/en_US/merch_fulfill/MerchFulfill_Datatypes.html#FileContents)—they're gzipped instead of zipped. I'm not sure if it matters, but the keys are also named differently.

Long story short, it seems there are at least two slightly different paths.

The current parser simply delegates to `MultiXml.parse`, which doesn't typecast values. This seems what we want to do here—detect and unpack values that contain binary data, perhaps saving the output to a `TempFile`.

To he honest, I'm not sure either how to go about this. Perhaps a first good step could be to simply add a section on this to the README instead of attempting to shoehorn some complex logic into the main library 🤔

**Comment by blairanderson** [comment]
Totally cool.

I’m actually having trouble with carton labels for multi-sku shipments.  


I do think it would be better just adding to the docs instead of implementing helpers because they might not get much direct usage. 

Thanks again for help
