### ISSUE TITLE
Can't figure out how to get multiple products.

### ISSUE THREAD

**Issue by hounsellal** [hakanensari/peddler#59]
I've tried passing an array into the ones that allow for multiple products. Doesn't work.

**Comment by hakanensari** [comment]
I'm assuming you are referring to the methods that take one or more ASINs or SKUs as argument, such as [this one](http://www.rubydoc.info/gems/peddler/MWS%2FProducts%2FClient%3Aget_my_price_for_asin). Note the splat operator in the method definition. That means you have to provide the list of IDs as is rather than as an array:

```ruby
res = client.get_my_price_for_asin('123', '456')
```
