### ISSUE TITLE
Please add FBAInbound_GetUniquePackageLabels.

### ISSUE THREAD

**Issue by noorani786** [hakanensari/peddler#73]
The API method to retrieve unique package labels is missing.  Can you please add?

http://docs.developer.amazonservices.com/en_US/fba_inbound/FBAInbound_GetUniquePackageLabels.html

Thanks!

**Comment by hakanensari** [comment]
It seems Amazon introduced in this API some new operations, including the two you posted here. It would be great if you took a stab at this with a PR. Otherwise, I'll do so when I get a chance.

**Comment by noorani786** [comment]
I have implemented this but getting an accessing denied when trying to push another branch onto your repository so I can create a pull request.  Here is the implementation:

 # Returns PDF document data for printing pallet labels for an inbound shipment
      #
      # @see http://docs.developer.amazonservices.com/en_US/fba_inbound/FBAInbound_GetPackageLabels.html
      # @param [String] shipment_id
      # @param [String] page_type
      # @param [String] number_of_pallets
      # @return [Peddler::XMLParser]
      def get_pallet_labels(shipment_id, page_type, opts = {})
        operation('GetPalletLabels')
          .add('ShipmentId' => shipment_id,
               'PageType' => page_type,
               'NumberOfPallets' => number_of_pallets)
        run
      end

**Comment by hakanensari** [comment]
> but getting an accessing denied when trying to push another branch onto your repository so I can create a pull request

I'm not sure if this is what the issue is, but you will want to clone the repository to your own account and push there. Then, you can create a pull request through the site.

The code looks good. It would be great if you could also fill the tests [here](https://github.com/hakanensari/peddler/blob/master/test/unit/mws/test_fulfillment_inbound_shipment_client.rb#L195-L199) and [here](https://github.com/hakanensari/peddler/blob/master/test/unit/mws/test_fulfillment_inbound_shipment_client.rb#L201-L205).

cc: #74
